package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BEFORE.
 */
public class Before {

    private Long id;
    private String date;
    private String json;

    public Before() {
    }

    public Before(Long id) {
        this.id = id;
    }

    public Before(Long id, String date, String json) {
        this.id = id;
        this.date = date;
        this.json = json;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

}
